### ISSUE TITLE
FATAL EXCEPTION: AsyncTask #1                                                                             java.lang.RuntimeException: An error occured while executing doInBackground()

### ISSUE THREAD

**Issue by arunkal** [lalongooo/VideoCompressor#10]
Below are the logs..
Android version 4.2.2
Devince Samsung SGH 1337

-------------------------------------------------------------------------------------------------------

02-10 01:11:11.784 21276-21276/? D/SELinux: selinux_knoxprecontexthook:  Calling  selinux_knoxprecontexthook for uid: 10196 isSystemServer: 0 seinfo: default pkgname com.lalongooo.videocompressor
02-10 01:11:11.784 21276-21276/? D/dalvikvm: Late-enabling CheckJNI
02-10 01:11:11.954 21276-21276/com.lalongooo.videocompressor D/ProgressBar: setProgress = 0
02-10 01:11:11.954 21276-21276/com.lalongooo.videocompressor D/ProgressBar: setProgress = 0, fromUser = false
02-10 01:11:11.954 21276-21276/com.lalongooo.videocompressor D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 100
02-10 01:11:11.954 21276-21276/com.lalongooo.videocompressor D/ProgressBar: setProgress = 0
02-10 01:11:11.954 21276-21276/com.lalongooo.videocompressor D/ProgressBar: setProgress = 0, fromUser = false
02-10 01:11:11.954 21276-21276/com.lalongooo.videocompressor D/ProgressBar: mProgress = 0mIndeterminate = true, mMin = 0, mMax = 100
02-10 01:11:11.964 21276-21276/com.lalongooo.videocompressor I/MainActivity: Display Name: VIDCAPTURE_20160210_010625.mp4
02-10 01:11:11.964 21276-21276/com.lalongooo.videocompressor I/MainActivity: Size: 21088090
02-10 01:11:13.275 21276-21276/com.lalongooo.videocompressor D/libEGL: loaded /system/lib/egl/libEGL_adreno200.so
02-10 01:11:13.275 21276-21276/com.lalongooo.videocompressor D/libEGL: loaded /system/lib/egl/libGLESv1_CM_adreno200.so
02-10 01:11:13.285 21276-21276/com.lalongooo.videocompressor D/libEGL: loaded /system/lib/egl/libGLESv2_adreno200.so
02-10 01:11:13.285 21276-21276/com.lalongooo.videocompressor I/Adreno200-EGL: <qeglDrvAPI_eglInitialize:265>: EGL 1.4 QUALCOMM build:  (CL3544079)
                                                                              Build Date: 03/28/13 Thu
                                                                              Local Branch: adreno_20130328
                                                                              Remote Branch: 
                                                                              Local Patches: 
                                                                              Reconstruct Branch: 
02-10 01:11:13.325 21276-21276/com.lalongooo.videocompressor D/OpenGLRenderer: Enabling debug mode 0
02-10 01:11:13.325 21276-21276/com.lalongooo.videocompressor D/ProgressBar: updateDrawableBounds: left = 0
02-10 01:11:13.335 21276-21276/com.lalongooo.videocompressor D/ProgressBar: updateDrawableBounds: top = 0
02-10 01:11:13.335 21276-21276/com.lalongooo.videocompressor D/ProgressBar: updateDrawableBounds: right = 144
02-10 01:11:13.335 21276-21276/com.lalongooo.videocompressor D/ProgressBar: updateDrawableBounds: bottom = 144
02-10 01:11:14.517 21276-21276/com.lalongooo.videocompressor D/GestureDetector: [Surface Touch Event] mSweepDown False, mLRSDCnt : -1 mTouchCnt : 5 mFalseSizeCnt:0
02-10 01:11:14.527 21276-21276/com.lalongooo.videocompressor D/MainActivity: Start video compression
02-10 01:11:14.537 21276-21378/com.lalongooo.videocompressor I/dalvikvm: Could not find method android.media.MediaCodec.createInputSurface, referenced from method com.lalongooo.videocompressor.video.MediaController.convertVideo
02-10 01:11:14.537 21276-21378/com.lalongooo.videocompressor W/dalvikvm: VFY: unable to resolve virtual method 555: Landroid/media/MediaCodec;.createInputSurface ()Landroid/view/Surface;
02-10 01:11:14.537 21276-21378/com.lalongooo.videocompressor D/dalvikvm: VFY: replacing opcode 0x74 at 0x033c
02-10 01:11:14.547 21276-21378/com.lalongooo.videocompressor I/dalvikvm: Could not find method android.media.MediaCodec.getInputBuffer, referenced from method com.lalongooo.videocompressor.video.MediaController.convertVideo
02-10 01:11:14.547 21276-21378/com.lalongooo.videocompressor W/dalvikvm: VFY: unable to resolve virtual method 558: Landroid/media/MediaCodec;.getInputBuffer (I)Ljava/nio/ByteBuffer;
02-10 01:11:14.547 21276-21378/com.lalongooo.videocompressor D/dalvikvm: VFY: replacing opcode 0x6e at 0x04e8
02-10 01:11:14.547 21276-21378/com.lalongooo.videocompressor I/dalvikvm: Could not find method android.media.MediaCodec.getOutputBuffer, referenced from method com.lalongooo.videocompressor.video.MediaController.convertVideo
02-10 01:11:14.547 21276-21378/com.lalongooo.videocompressor W/dalvikvm: VFY: unable to resolve virtual method 560: Landroid/media/MediaCodec;.getOutputBuffer (I)Ljava/nio/ByteBuffer;
02-10 01:11:14.547 21276-21378/com.lalongooo.videocompressor D/dalvikvm: VFY: replacing opcode 0x6e at 0x057f
02-10 01:11:14.557 21276-21378/com.lalongooo.videocompressor I/dalvikvm: Could not find method android.media.MediaCodec.signalEndOfInputStream, referenced from method com.lalongooo.videocompressor.video.MediaController.convertVideo
02-10 01:11:14.557 21276-21378/com.lalongooo.videocompressor W/dalvikvm: VFY: unable to resolve virtual method 566: Landroid/media/MediaCodec;.signalEndOfInputStream ()V
02-10 01:11:14.557 21276-21378/com.lalongooo.videocompressor D/dalvikvm: VFY: replacing opcode 0x74 at 0x076a
02-10 01:11:14.637 21276-21378/com.lalongooo.videocompressor V/MediaExtractor: Autodetected media content as 'video/mp4' with confidence 0.40
02-10 01:11:14.647 21276-21378/com.lalongooo.videocompressor I/OMXClient: Using client-side OMX mux.
02-10 01:11:14.697 21276-21378/com.lalongooo.videocompressor E/tmessages: codec = OMX.qcom.video.encoder.avc manufacturer = samsungdevice = SAMSUNG-SGH-I337
02-10 01:11:14.697 21276-21378/com.lalongooo.videocompressor E/tmessages: colorFormat = 21
02-10 01:11:14.697 21276-21378/com.lalongooo.videocompressor I/ACodec:  Now uninitialized
02-10 01:11:14.697 21276-21399/com.lalongooo.videocompressor I/OMXClient: Using client-side OMX mux.
02-10 01:11:14.727 21276-21399/com.lalongooo.videocompressor I/ACodec: [OMX.qcom.video.encoder.avc] Now Loaded
02-10 01:11:14.727 21276-21399/com.lalongooo.videocompressor I/ACodec: setupVideoEncoder succeeded
02-10 01:11:14.727 21276-21399/com.lalongooo.videocompressor I/ACodec: [OMX.qcom.video.encoder.avc] Now Loaded->Idle
02-10 01:11:14.747 21276-21378/com.lalongooo.videocompressor I/ACodec:  Now uninitialized
02-10 01:11:14.757 21276-21405/com.lalongooo.videocompressor I/OMXClient: Using client-side OMX mux.
02-10 01:11:14.757 21276-21399/com.lalongooo.videocompressor I/ACodec: [OMX.qcom.video.encoder.avc] Now Idle->Executing
02-10 01:11:14.757 21276-21405/com.lalongooo.videocompressor I/ACodec: [OMX.qcom.video.decoder.avc] Now Loaded
02-10 01:11:14.757 21276-21399/com.lalongooo.videocompressor I/ACodec: [OMX.qcom.video.encoder.avc] Now Executing
02-10 01:11:14.807 21276-21405/com.lalongooo.videocompressor I/ACodec: [OMX.qcom.video.decoder.avc] Now Loaded->Idle
02-10 01:11:14.817 21276-21405/com.lalongooo.videocompressor I/ACodec: [OMX.qcom.video.decoder.avc] Allocating 10 buffers from a native window of size 3137536 on output port
02-10 01:11:14.967 21276-21405/com.lalongooo.videocompressor I/ACodec: [OMX.qcom.video.decoder.avc] Now Idle->Executing
02-10 01:11:15.127 21276-21405/com.lalongooo.videocompressor I/ACodec: [OMX.qcom.video.decoder.avc] Now Executing
02-10 01:11:15.317 21276-21378/com.lalongooo.videocompressor E/tmessages: newFormat = {height=1080, what=1869968451, color-format=2141391875, slice-height=1088, crop-left=0, width=1920, crop-bottom=1079, crop-top=0, mime=video/raw, stride=1920, crop-right=1919}
02-10 01:11:15.347 21276-21405/com.lalongooo.videocompressor E/BufferQueue: [unnamed-21276-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=9 undequeudCount=0)
02-10 01:11:15.347 21276-21405/com.lalongooo.videocompressor E/ACodec: dequeueBuffer failed.
02-10 01:11:15.357 21276-21378/com.lalongooo.videocompressor W/dalvikvm: No implementation found for native Lcom/lalongooo/videocompressor/video/MediaController;.convertVideoFrame:(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIII)I
02-10 01:11:15.417 21276-21378/com.lalongooo.videocompressor E/tmessages: time = 819
02-10 01:11:15.417 21276-21378/com.lalongooo.videocompressor W/dalvikvm: threadid=12: thread exiting with uncaught exception (group=0x41416ac8)
02-10 01:11:15.427 21276-21378/com.lalongooo.videocompressor E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                               java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                   at android.os.AsyncTask$3.done(AsyncTask.java:299)
                                                                                   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
                                                                                   at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:239)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                                   at java.lang.Thread.run(Thread.java:856)
                                                                                Caused by: java.lang.UnsatisfiedLinkError: Native method not found: com.lalongooo.videocompressor.video.MediaController.convertVideoFrame:(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIII)I
                                                                                   at com.lalongooo.videocompressor.video.MediaController.convertVideoFrame(Native Method)
                                                                                   at com.lalongooo.videocompressor.video.MediaController.convertVideo(MediaController.java:589)
                                                                                   at com.lalongooo.videocompressor.MainActivity$VideoCompressor.doInBackground(MainActivity.java:124)
                                                                                   at com.lalongooo.videocompressor.MainActivity$VideoCompressor.doInBackground(MainActivity.java:113)
                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                                                   at java.lang.Thread.run(Thread.java:856) 
02-10 01:11:25.067 21276-21276/com.lalongooo.videocompressor I/Choreographer: Skipped 574 frames!  The application may be doing too much work on its main thread.
02-10 01:11:27.579 21276-21378/com.lalongooo.videocompressor I/Process: Sending signal. PID: 21276 SIG: 9

**Comment by arunkal** [comment]
Where is the JNI library opened? I deleted all the JNI libs and still the compilation went through and further I was able to use the app. 
so looks like the jni libs are not used at all

**Comment by lalongooo** [comment]
Hi @arunkal, sorry for the late reply. Did you manage to fix this?
