### ISSUE TITLE
Issue in 4.1.1

### ISSUE THREAD

**Issue by harshflipk** [lalongooo/VideoCompressor#4]
I am facing this issue on 4.1.1 version. I have forked your project as it is and running on the device. Do we have to do **Syste.loadlibrary()** somewhere and proceed for api versions <18. I have run the project in lollipop and it is doing fine.

==============================================================================
556 23280-23429/com.lalongooo.videocompressor E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                               java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                   at android.os.AsyncTask$3.done(AsyncTask.java:299)
                                                                                   at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
                                                                                   at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
                                                                                   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                                   at **java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                                   at java.lang.Thread.run(Thread.java:856)
                                                                                Caused by: java.lang.UnsatisfiedLinkError: Native method not found: com.lalongooo.videocompressor.video.MediaController.convertVideoFrame:(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIII)I**
                                                                                   at com.lalongooo.videocompressor.video.MediaController.convertVideoFrame(Native Method)
                                                                                   at com.lalongooo.videocompressor.video.MediaController.convertVideo(MediaController.java:593)
                                                                                   at com.lalongooo.videocompressor.MainActivity$VideoCompressor.doInBackground(MainActivity.java:124)
                                                                                   at com.lalongooo.videocompressor.MainActivity$VideoCompressor.doInBackground(MainActivity.java:113)
                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                                                   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
                                                                                   at java.lang.Thread.run(Thread.java:856) 

==============================================================================
**I tried doing System.loadlibrary("webp") following error occurred**

11-18 14:59:32.377 23545-23545/com.lalongooo.videocompressor E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               java.lang.ExceptionInInitializerError
                                                                                   at java.lang.Class.newInstanceImpl(Native Method)
                                                                                   at java.lang.Class.newInstance(Class.java:1319)
                                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:982)
                                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:967)
                                                                                   at android.app.LoadedApk.makeApplication(LoadedApk.java:496)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4291)
                                                                                   at android.app.ActivityThread.access$1300(ActivityThread.java:149)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                   at android.os.Looper.loop(Looper.java:153)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5086)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: java.lang.UnsatisfiedLinkError: Couldn't load webp: findLibrary returned null
                                                                                   at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                                                   at java.lang.System.loadLibrary(System.java:535)
                                                                                   at com.lalongooo.videocompressor.VideoCompressorApplication.<clinit>(VideoCompressorApplication.java:13)
                                                                                   at java.lang.Class.newInstanceImpl(Native Method) 
                                                                                   at java.lang.Class.newInstance(Class.java:1319) 
                                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:982) 
                                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:967) 
                                                                                   at android.app.LoadedApk.makeApplication(LoadedApk.java:496) 
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4291) 
                                                                                   at android.app.ActivityThread.access$1300(ActivityThread.java:149) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                   at android.os.Looper.loop(Looper.java:153) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5086) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 

==============================================================================

**Comment by harshflipk** [comment]
I guess you have already mentioned it not being working on below 19 devices. Hence closing the issue.
