### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by harshwardhan91** [lalongooo/VideoCompressor#6]
Can you please show the proguard file that is to be used for the project to run.

Till now I have tried this 

===========================
-dontwarn com.googlecode.mp4parser.**

-dontwarn com.coremedia.iso.boxes.**

-keep class com.coremedia.iso.boxes.**{ *; }

-dontwarn com.mp4parser.**

-keep class isoparser-1.0.6.** { *; }

-dontwarn isoparser-1.0.6.**

-keep public class * implements com.coremedia.iso.boxes.Box

=================================================================

but still I am getting this error 

=================================================
E/AndroidRuntime( 4802): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 4802): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime( 4802): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 4802): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 4802): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 4802): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime( 4802): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 4802): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 4802): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 4802): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/aspectj/runtime/reflect/Factory;
E/AndroidRuntime( 4802): 	at com.coremedia.iso.boxes.FileTypeBox.c(FileTypeBox.java:1)
E/AndroidRuntime( 4802): 	at com.coremedia.iso.boxes.FileTypeBox.<clinit>(FileTypeBox.java:1)
E/AndroidRuntime( 4802): 	at in.app.util.video.MP4Builder.a(MP4Builder.java:164)
E/AndroidRuntime( 4802): 	at in.app.util.video.MP4Builder.a(MP4Builder.java:71)
E/AndroidRuntime( 4802): 	at in.app.util.video.MediaController.a(MediaController.java:323)
E/AndroidRuntime( 4802): 	at in.app.jobs.VideoUploadJob$VideoCompressor.doInBackground(VideoUploadJob.java:100)
E/AndroidRuntime( 4802): 	at in.app.jobs.VideoUploadJob$VideoCompressor.doInBackground(VideoUploadJob.java:85)
E/AndroidRuntime( 4802): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime( 4802): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 4802): 	... 4 more
E/AndroidRuntime( 4802): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.aspectj.runtime.reflect.Factory" on path: DexPathList[[zip file "/data/app/in.flatchat-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime( 4802): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 4802): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 4802): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime( 4802): 	... 13 more
E/AndroidRuntime( 4802): 	Suppressed: java.lang.ClassNotFoundException: org.aspectj.runtime.reflect.Factory
E/AndroidRuntime( 4802): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 4802): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime( 4802): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime( 4802): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime( 4802): 		... 14 more
E/AndroidRuntime( 4802): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

====================================================================

It runs fine in debug mode, but for release with proguard compression is failing

**Comment by lalongooo** [comment]
Currently I'm not using proguard for this project, so...I cannot share a proguard file with you :cry:

**Comment by MuhammadAbidzarAbdussalam** [comment]
I have the same issue, could you like to show me how to solve this
